global:
  dbRootPassword: "rootpasswd"
  dbUser: "mmuser"
  dbPassword: "passwd"
  dbName: "mattermost"
  mattermostLicense: "THIS STRING SHOULD BE REPLACED WITH THE CONTENTS OF YOUR LICENSE FILE"

mattermost-app:
  replicaCount: 2
  image:
    tag: daily-build
  
mattermost-proxy:
  replicaCount: 2

