apiVersion: v1
kind: Service
metadata:
  name: mattermost-proxy
  labels:
    app: mattermost
spec:
  ports:
    - port: 80
  selector:
    app: mattermost
    tier: proxy
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-proxy
  labels:
    app: mattermost
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mattermost
        tier: proxy
    spec:
      containers:
      - image: mattermost-nginx:v1
        name: mattermost-proxy
        ports:
        - containerPort: 80
          name: proxy