apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-first-run-job
  labels:
    app: mattermost
spec:
  template:
    metadata:
      name: mattermost-first-run-job
    spec:
      containers:
      - name: mattermost-first-run-job
        image: mattermost-first-run-job:v1
        command: ["grafana-config.sh"]
      restartPolicy: Never