apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-load-test
  labels:
    app: mattermost
spec:
  template:
    metadata:
      name: mattermost-load-test
    spec:
      containers:
      - name: mattermost-load-test
        image: mattermost-load-test:v1
        command: ["load-test.sh"]
        volumeMounts:
        - mountPath: /mattermost/data
          name: data
        - mountPath: /mattermost/config
          name: config
      volumes:
          - name: data
            emptyDir: {}
          - name: config
            configMap:
              name: mattermost-config
              items:
              - key: config.json
                path: config.json
      restartPolicy: Never