apiVersion: v1
kind: Service
metadata:
  name: mattermost-db
  labels:
    app: mattermost
spec:
  ports:
    - port: 3306
  selector:
    app: mattermost
    tier: db
  type: NodePort
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-db-pv-claim
  labels:
    app: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-db
  labels:
    app: mattermost
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mattermost
        tier: db
    spec:
      containers:
      - image: mattermost-db:v1
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-db-root-password
              key: db-root-password.txt
        - name: MYSQL_DATABASE
          value: "mattermost"
        - name: MYSQL_USER
          value: "mmuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-db-password
              key: db-password.txt
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
        - name: mattermost-db-persistent-storage
          mountPath: /var/lib/db
      volumes:
      - name: mattermost-db-persistent-storage
      #   persistentVolumeClaim:
      #    claimName: mattermost-db-pv-claim