apiVersion: v1
kind: Service
metadata:
  name: mattermost-app
  labels:
    app: mattermost
spec:
  ports:
    - port: 8065
  selector:
    app: mattermost
    tier: app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mattermost-app
  labels:
    app: mattermost
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mattermost
        tier: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8067"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - image: mattermost-app:v1
        name: mattermost-app
        ports:
        - containerPort: 8065
          name: api
        - containerPort: 8067
          name: metrics
        - containerPort: 8075
          name: cluster
        volumeMounts:
        - mountPath: /mattermost/data
          name: data
        - mountPath: /mattermost/config
          name: config
      volumes:
          - name: data
            emptyDir: {}
          - name: config
            configMap:
              name: mattermost-config
              items:
              - key: config.json
                path: config.json